language: c

os:
 - linux
 - osx

compiler:
 - clang
 - gcc
 - g++

script:
  - >
    if ["$TRAVIS_OS_NAME" = 'linux']
      then
        sudo apt-get install libpthread-stubs0-dev
    fi
  - make test
